version: "3.9"
services:
  dxe:
    build:
      context: .
      args:
        EXEC: ${EXEC:-discord-xiv-emotes}
    environment:
      DATABASE_URL: postgres://postgres:password@dxe-db/postgres
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    depends_on:
      - "dxe-db"
    command: ["./wait-for-it.sh", "dxe-db:5432", "--", "./discord-xiv-emotes"]
  dxe-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
